# Workflow name
name: Build
on:
  # When it will be triggered
  # And in which branch
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
# Where will they run
jobs:
  lint:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run lint
        uses: ./gradlew lintDebug

      - name: Uploat lint violations
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html